import type { Metadata } from "next";
// app/layout.tsx 또는 _app.tsx (Next.js 13+)
import { Noto_Sans_KR } from "next/font/google";

import "./globals.css";
import Navigation from "@/components/Navigation";
import SessionProvider from "./Provider";

const notoSansKR = Noto_Sans_KR({
  subsets: ["latin"], // 한글 지원
  weight: ["100", "300", "400", "500", "700", "900"], // 원하는 폰트 두께
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansKR.className}>
        <SessionProvider>
          <Navigation></Navigation>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
